name: deploy

on:
  push:
    branches:
      - 27-feature-ci-구축

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Istall modules
        run: npm install --force

      - name: Build
        run: npm run build
